controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    armbot_controller:
      type: ros2_control_demo_example_7/RobotController


armbot_controller:
  ros__parameters:
    joints:
      - Revolute_3
      - Revolute_28
      - Revolute_40
      - Revolute_44
      - Revolute_48
      - Revolute_65

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
