# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

group_controller:
  ros__parameters:
    joints:
      - Revolute 3
      - Revolute 28
      - Revolute 40
      - Revolute 44
      - Revolute 48
      - Revolute 65
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity